tijsverkoyen/CssToInlineStyles

src/CssToInlineStyles.php

Css properties with base64 encoded content contain a ';' and they were not managed by the property spliting function.
Example of breaked input that works now:
'background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIUAAAAgCAYAA...);'

Fix properties split on base64 encoded url content

---

src/CssToInlineStyles.php
tests/CssToInlineStylesTest.php

Manipulating HTML using regular expressions is error prone.
The code in cleanupHTML() matches more that it should and converts e.g. `<p> id="123" </p>` to `<p> </p>` even though it should be left unchanged.
This PR changes cleanupHTML() to use DOM methods instead.

Use DOM instead of regexp in cleanupHTML()

---

src/CssToInlineStyles.php

The original BSD license isn't compatible with the GPL license that I use with WordPress plugins but the revised BSD license you have in `LICENSE.md` [*is* compatible](http://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_.28.22Revised_BSD_License.22.2C_.22New_BSD_License.22.2C_or_.22Modified_BSD_License.22.29). I wanted to clarify for future users who want to include this in their projects and need to know exactly which license you're using.

Clarifying License Type

---

src/CssToInlineStyles.php
tests/CssToInlineStylesTest.php

I've cherry-picked @barryvdh's test case and @rvock's fix and put them in a single pull request for your convenience. This should fix issue #96, making sure the XML header is properly removed from the output.

Fixed stripping of XML header when outputting XHTML

---

src/CssToInlineStyles.php

SyntaxErrorException extends ParseException. Now also other exceptions are caught.
In my case:
> Fatal error:  Uncaught exception 'Symfony\Component\CssSelector\Exception\ExpressionErrorException' with message 'Pseudo-class "active" not supported.' in /var/www/html/inlinetest/vendor/symfony/css-selector/XPath/Translator.php:259

[2.0] Use ExceptionInterface instead of SyntaxErrorException

---

src/CssToInlineStyles.php
tests/CssToInlineStylesTest.php

DomDocument::loadHTML loads UTF-8 html as iso-8859-1 unless xml header is set
http://stackoverflow.com/a/8218649/1703973

DOMDocument::loadHTML() UTF-8 issue

---

src/CssToInlineStyles.php
tests/CssToInlineStylesTest.php

This solves the issues with self-closing tags (`<br>` going to `<br></br>`) and assists with utf-8 encoding.
@techi602 I think this should solve all the utf-8 encoding issues?

Save as html instead of xml. Fixes self-closing tags and utf-8 encoding.

---

src/Css/Processor.php
tests/Css/ProcessorTest.php

The tag name must be followed by a whitespace when we have attributes.
Otherwise, it will be a different tag name.
The test ``testWeirdTagsInHtml`` covered this, because it matched ``</stylesheet>\n        <style>\n            p { color: #F00; }\n`` otherwise.

Fix the detection of style tags

---

composer.json

This allows knowing the min requirement.
The code tells me that it is at least 5.4 (it uses syntaxes incompatible with 5.3). I went for 5.5 here, because 5.4 was removed from Travis.

Add the PHP requirement in the composer.json

---

tests/Css/ProcessorTest.php

When reading the regex, I first wondered whether it supported multiple comments properly. After reading it thoroughly, I figured out it does, because of using a non-greedy quantifier.
But to ensure that things are not broken by mistake in the future, I added a test covering this (so that removing the non-greedy flag by mistake would make the test fail)

Add a test for the removal of comments

---

src/CssToInlineStyles.php

Initializing the CSS converter is a bit heavy. Reusing the same instance for all rules instead of creating a new one each time leads to a major performance boost (-20% time spent when running the example).
This optimization is possible only when using the Symfony CssSelector component 2.8+. The old API from Symfony 2.7 and older does not allow to perform it, as it exposes only a static method.

Reuse the same CssSelectorConverter

---

src/Css/Processor.php
tests/Css/ProcessorTest.php
tests/Css/test.css

On big CSS files, the regex deleting media queries was reaching the pcre jit stack limit, breaking the library on PHP 7 by default (as pcre.jit is enabled by default).
Note that this could also reach the PCRE backtracking limit in non-JIT mode (so both on 5.x and 7.x), but this would require a file much bigger than the one I added in the testsuite (because PHP configures the PCRE backtrack limit to 1000000 by default, but it would fail on this big file when setting it to 1000 without my patch, while it works with the patch)

Use possessive quantifiers to avoid reaching PCRE limits

---

src/CssToInlineStyles.php

Storing the element CSS properties in memory during the processing is faster than serializing them to store them in the DOM and then unserializing them back again each time.
When using it for the example, I get a nice performance improvement. Applying this patch on top of #152 gives me an additional 6% win.

Refactor the storage of the computed properties

---

src/Css/Rule/Processor.php
src/CssToInlineStyles.php
tests/CssToInlineStylesTest.php

This PR solves the same issues as #159 and #155, and more.
It assigns all issues reported in https://github.com/tijsverkoyen/CssToInlineStyles/issues/140.
This pr too takes priority into account by sorting the rules via the already available method, but sorting happens later (when you need it) when rules are inserted, not when they are parsed and collected.
When processing properties it does not just overwrite the properties but it unsets and adds them.
This ensures that the order is correct and the css like the one below is processed correctly too:
```css
td  {
padding: 0;
}
td  {
padding-bottom: 20px;
}
td  {
padding: 0;
}
```
The specificity tests are updated to reflect the changes made with ordering the rules and properties.
It also tests all the different uses cases mentioned in …

Better ordering of style rules and properties

---

src/Css/Processor.php
tests/Css/ProcessorTest.php

When the <style> block is inside a html comment, it's contents should
not be inlined.

Remove styles that are inside html comments

---

composer.json
tests/Css/ProcessorTest.php
tests/Css/Property/ProcessorTest.php
tests/Css/Property/PropertyTest.php
tests/Css/Rule/ProcessorTest.php
tests/Css/Rule/RuleTest.php
tests/CssToInlineStylesTest.php

I use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCases. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
I just need to bump PHPUnit version to [`~4.8.35`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4835---2017-02-06) and [`~5.7`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-5.7.md#570---2016-12-02), that support this namespace.

Use PHPUnit\Framework\TestCase instead of PHPUnit_Framework_TestCase

---

.travis.yml
composer.json

A quick merge would be greatly appreciated as the CI of symfony/symfony needs this change to be green. Thanks in advance!
see e.g. https://travis-ci.org/symfony/symfony/jobs/587127531

Allow Symfony 5 to unlock the CI of symfony/symfony

---

composer.json

Staring yesterday you can install Symfony 6.0 (if you allow unstable dependencies). 
I know Symfony 6.0 is not released yet (it will be released in November 2021). But since this package is required by some CI jobs of symfony/symfony I would appreciate if this PR was merged.

Allow Symfony 6.0

---

phpunit.xml.dist

This allows running PHPUnit with code coverage enabled.
In modern PHPUnit versions, the filter config is mandatory otherwise the code coverage is skipped.

Add the code coverage filtering config in the PHPUnit config

---

.gitattributes

Currently the github workflow is present in the published package.

Mark .github directory as ignored for exports

---

.github/workflows/ci.yml

Let's build also on Windows to prevent issues similar to #204 in the future.

CI: build also on Windows

---

tests/Css/Rule/RuleTest.php

Otherwise, the test suite fails with recent version of PHPUnit (10).

Ensure file name matches class name

---

.github/workflows/ci.yml
composer.json

Starting to work on adding phpstan in this project, I figured out that it would be a lot simpler to setup if our min PHP version was compatible with the min version required by phpstan (so that we can use a normal `require-dev` to install it).
As we have an unreleased version bump already (from PHP 5.3 to PHP 7.2.5), I'm updating it to bump to 7.4 instead (which is still outside the list of maintained PHP versions, but still represents 5% of installs in the packagist stats so I'm keeping it as it does not annoy me to keep support for it).

Bump the min PHP version to PHP 7.4

---

.gitattributes
.github/workflows/ci.yml
.gitignore
composer.json
phpstan.dist.neon
src/Css/Processor.php
src/Css/Property/Processor.php
src/Css/Property/Property.php
src/Css/Rule/Processor.php
src/CssToInlineStyles.php
tests/Css/ProcessorTest.php
tests/Css/Property/ProcessorTest.php
tests/Css/Property/PropertyTest.php
tests/Css/Rule/ProcessorTest.php
tests/Css/Rule/RuleTest.php
tests/CssToInlineStylesTest.php

Add static analysis with phpstan
